name: Django CI with pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: medbook_user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U medbook_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_DB: test_db
      POSTGRES_USER: medbook_user
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: medbook.settings  # Changed from src.medbook.settings
      SECRET_KEY: test
      DEBUG: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install psycopg2-binary pytest-django

    - name: Wait for PostgreSQL to be ready
      run: |
        timeout 20s bash -c 'until pg_isready -h localhost -p 5432 -U medbook_user; do sleep 1; done'
        echo "PostgreSQL is ready!"
    
    - name: Run migrations
      working-directory: ./backend/src  # Set working directory
      run: |
        python manage.py migrate

    - name: Run tests with pytest
      working-directory: ./backend/src  # Set working directory
      run: |
        PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/backend/src pytest